# Generated by Django 5.2.8 on 2026-02-15 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
